# 开发环境配置文件
# 应用服务 WEB 访问端口
server:
  port: 8080
# 日志配置
logging:
  config: logback.xml
  level:
    com:
      lizhankang:
        springbootdemo:
          dao: trace

# 数据库地址
datasource:
  url: localhost:3306/springboot-demo
spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 1234567890
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.lizhankang.springbootdemo.dao.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml

# 配置信息
url:
  orderUrl: http://localhost:9002
  userUrl: http://localhost:9003
  shoppingUrl: http://localhost:9004
